name: Continuous Integration with GitHub Actions

on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up JDK 18
      uses: actions/setup-java@v2
      with:
        java-version: '18'
        distribution: 'adopt'
        cache: maven
    
    - name: Build Application jar
      working-directory: ../api-rest-spring
      run: mvn clean package -e
    
    - name: Docker compose build
      run: docker compose build
      
    - name: Push to Docker Hub Container Registry
      run: docker images
        
